version: 2.1

orbs:
    node: circleci/node@4.0.0

jobs:
    setup:
        doker:
          - image: circleci/node:12.18.3-browser
        steps:
          - checkout
          - node/install:
              install-npm: true
            - run: node --version
            - run: npm --version

workflows:
  ci:
    jobs:
    - setup